test:
	find ./example/* -name '*_genembed.go' -print0 | xargs -0 rm

	go install -v github.com/gebv/go-embed/genembed
	go generate -v -x github.com/gebv/go-embed/...

	go test -v -count=1 -race github.com/gebv/go-embed/...
	go test -v -count=1 -covermode=count -coverprofile=go-embed.cover github.com/gebv/go-embed/...

	go vet ./...

lint:
	golangci-lint run ./...
