name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test:
    name: Test
    strategy:
      matrix:
        os:
          - ubuntu-latest
        go-version:
          - 1.13.x
          - 1.14.x
          - 1.15.x
    runs-on: ${{ matrix.os }}
    steps:

    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
      id: go

    - name: Set environment variables
      run: |
        echo "::set-env name=GOPATH::$GITHUB_WORKSPACE/go"
        echo "::add-path::$GITHUB_WORKSPACE/go/bin"
        echo "::set-env name=WORKDIR::$GITHUB_WORKSPACE/go/src/github.com/gebv/genembed"

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        path: ${{ env.WORKDIR }}

    # TODO: add linter

    - name: Test
      working-directory: ${{ env.WORKDIR }}
      run: make test

    - name: Check code changes
      working-directory: ${{ env.WORKDIR }}
      run: |
        go mod tidy
        git status
        git diff --exit-code

    - name: Upload coverage metrics
      working-directory: ${{ env.WORKDIR }}
      run: |
        bash <(curl -s https://codecov.io/bash) -X fix -f coverage.txt
