name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test:
    name: Test
    strategy:
      matrix:
        os:
          - ubuntu-latest
        go-version:
          - 1.13.x
          - 1.14.x
          - 1.15.x
    runs-on: ${{ matrix.os }}
    steps:

    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    # - name: Lint
    #   uses: golangci/golangci-lint-action@v2
    #   with:
    #     version: v1.29

    - name: Test
      run: make test

    - name: Check code changes
      run: |
        pwd && go mod tidy && git checkout go.sum
        git status
        git diff --exit-code
